### ISSUE TITLE
Should messages carry a Message ID

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opamp-spec#18]
A unique ID may be necessary for associating a response to a request. For example, when a Server indicates to an Agent that it should retry a request, how does the Agent know which request should be retried? A unique ID would be helpful in resolving ambiguity in such cases.

**Comment by tigrannajaryan** [comment]
It was in the early versions of the spec then I removed them because I was unable to come up with an example where having the message id was necessary. It is still in the Open Questions list since I am not sure.

>For example, when a Server indicates to an Agent that it should retry a request, how does the Agent know which request should be retried?

We don't have this need in the protocol currently. We have a BAD_REQUEST response, which is about a specific message but Agent doesn't need to know which one specifically because it does not need to retry. We also have UNAVAILABLE response, which is generic, again Agent doesn't need to know which message specifically caused this. Likewise for UNKNOWN error response.

So, while it does seem like this could be useful I was unable to describe exactly how will the agent and server use the message id. The only way I can think of is for logging the message id to make troubleshooting easier. Perhaps this alone is a justification.

However, do note that there are some complications possible. The protocol currently does not require that every Agent request has exactly one Server response. The Agent may send a message to which the Server responds with more than one. Moreover the Server may send messages to the Agent without the Agent asking for anything. In these situations it is not entirely clear what the message ids should be.
